services:
  grafana-slack-bot:
    build:
      context: .
      network: host
    container_name: grafana-slack-bot
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./.env:/app/.env
      - ./sites.json:/app/sites.json
      - ./grafana_auth_state.json:/app/grafana_auth_state.json
      - ./core:/app/core
      - ./engines:/app/engines
      - ./scheduler:/app/scheduler
      - ./web:/app/web
      - ./main.py:/app/main.py
    environment:
      - PYTHONUNBUFFERED=1
