services:
  grafana-slack-bot:
    build:
      context: .
      network: host
    container_name: grafana-slack-bot
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./.env:/app/.env
      - ./sites.json:/app/sites.json
    environment:
      - PYTHONUNBUFFERED=1
